package net.kaupenjoe.tutorialmod.client;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

public class ClientAltarData {
    private static int requiredItem;

    public static void set(int requiredItem) {
        ClientAltarData.requiredItem = requiredItem;
    }
    static Item randomItem = Items.STICK;
    Item[] items = {
            Items.COBBLESTONE,
            Items.GRANITE,
            Items.ANDESITE,
            Items.DIORITE,
            Items.SMOOTH_STONE,
            Items.OAK_LOG,
            Items.DARK_OAK_LOG,
            Items.SPRUCE_LOG,
            Items.ACACIA_LOG,
            Items.JUNGLE_LOG,
            Items.BIRCH_LOG,
            Items.PODZOL,
            Items.ICE,
            Items.PACKED_ICE,
            Items.NETHER_WART_BLOCK,
            Items.SAND,
            Items.GRAVEL,
            Items.OBSIDIAN,
            Items.TERRACOTTA,
            Items.DIRT,
            Items.GLASS,
            Items.PRISMARINE_BRICKS,
            Items.PRISMARINE,
            Items.NETHERRACK,
            Items.CLAY,
            Items.BRICKS,
            Items.SOUL_SAND,
            Items.BLACKSTONE,
            Items.BASALT,
            Items.MAGMA_BLOCK,
            Items.END_STONE,
            Items.WHITE_WOOL,
            Items.NETHER_BRICKS,
            Items.PURPUR_BLOCK,
            Items.SNOW_BLOCK,
            Items.DARK_PRISMARINE,
            Items.WHITE_CONCRETE,
            Items.GLOWSTONE_DUST,
            Items.LAPIS_LAZULI,
            Items.CHARCOAL,
            Items.COAL,
            Items.GOLD_INGOT,
            Items.IRON_INGOT,
            Items.REDSTONE,
            Items.DIAMOND,
            Items.EMERALD,
            Items.NETHERITE_SCRAP,
            Items.QUARTZ,
            Items.GUNPOWDER,
            Items.SUGAR_CANE,
            Items.CARROT,
            Items.WHEAT,
            Items.POTATO,
            Items.PUMPKIN,
            Items.MELON,
            Items.BONE,
            Items.ROTTEN_FLESH,
            Items.STRING,
            Items.ENDER_PEARL,
            Items.PORKCHOP,
            Items.BEEF,
            Items.CHICKEN,
            Items.FEATHER,
            Items.CACTUS,
            Items.WHEAT_SEEDS,
            Items.LEATHER,
            Items.SNOWBALL,
            Items.SLIME_BALL,
            Items.COD,
            Items.KELP,
            Items.BAMBOO,
            Items.CHORUS_FRUIT,
            Items.BROWN_MUSHROOM,
            Items.RED_MUSHROOM,
            Items.VINE,
            Items.SUNFLOWER,
            Items.LILAC,
            Items.ROSE_BUSH,
            Items.PEONY,
            Items.HONEY_BOTTLE,
            Items.SWEET_BERRIES,
            Items.APPLE,
            Items.SEA_PICKLE,
            Items.WITHER_ROSE,
            Items.COCOA_BEANS,
            Items.FLINT,
            Items.INK_SAC,
            Items.NETHER_WART,
            Items.BLAZE_ROD,
            Items.NETHER_STAR,
            Items.DRAGON_HEAD,
            Items.SADDLE,
            Items.WITHER_SKELETON_SKULL,
            Items.CAKE,
            Items.NAUTILUS_SHELL,
            Items.HEART_OF_THE_SEA,
            Items.PHANTOM_MEMBRANE,
            Items.TRIDENT,
            Items.TURTLE_EGG,
            //Items.MUSIC_DISC_,
            Items.HONEYCOMB,
            //Items.QUARKSOUL_BEAD,
            //Items.QUARKDIAMOND_HEART,
            Items.POISONOUS_POTATO,
            Items.BELL,
            Items.COBWEB,
    };


    public static int getRequiredItem() {
        return requiredItem;
    }
}
